version: '3'
services:
    postgres:
        container_name: 'clean-ecommerce-postgresql'
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_NAME}'
